name: Release
on:
  workflow_dispatch:
    inputs:
      ref:
        description: "tag"
        required: true
        default: ""
        type: string

jobs:
  package:
    runs-on: ubuntu-latest
    environment: release
    steps:
      - name: Create github app token
        uses: actions/create-github-app-token@1b10c78c7865c340bc4f6099eb2f838309f1e8c3 # v3.1.1
        id: app-token
        with:
          client-id: ${{ vars.CLIENT_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}

      - name: Set git config
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git config --global url."https://x-access-token:${GITHUB_TOKEN}@github.com/".insteadOf https://github.com/
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}

      - uses: actions/checkout@v6
        with:
          token: ${{ steps.app-token.outputs.token }}
          persist-credentials: false

      - name: Push tag
        run: |
          git tag -a "${REF_NAME}" -m "Release ${REF_NAME}"
          git push origin "${REF_NAME}"
        env:
          REF_NAME: ${{ inputs.ref }}

      - name: Create Release
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3  # v9.0.0
        id: create_release
        env:
          REF_NAME: ${{ inputs.ref }}
        with:
          github-token: ${{ secret.GITHUB_TOKEN }}
          script: |
            const release = await github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: process.env.REF_NAME,
              name: `Release ${process.env.REF_NAME}`,
              body: 'update',
              draft: false,
              prerelease: false
            })
            return release.data.id

      - name: Upload Release Asset
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3  # v9.0.0
        env:
          RELEASE_ID: ${{ steps.create_release.outputs.result }}
        with:
          github-token: ${{ steps.app-token.outputs.token }}
          script: |
            const fs = require('fs')
            await github.rest.repos.uploadReleaseAsset({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: process.env.RELEASE_ID,
              name: 'build.tar.bz2',
              data: fs.readFileSync('./build.tar.bz2')
            })